# Generated by Django 6.1.2 on 2026-10-07 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("key", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_path", models.CharField(db_index=True, max_length=255)),
                ("task_name", models.CharField(max_length=255)),
                ("backend", models.CharField(max_length=64)),
                ("queue_name", models.CharField(db_index=True, max_length=128)),
                ("priority", models.IntegerField(default=0)),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("enqueue", "Enqueued"),
                            ("retry", "Retry"),
                            ("schedule", "Schedule"),
                            ("manual", "Manual"),
                        ],
                        default="enqueue",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unique_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_dashboard", "Can view the Overseer dashboard"),
                    ("manage_jobs", "Can retry, cancel and dismiss jobs"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_start", models.DateTimeField(db_index=True)),
                ("queue_name", models.CharField(max_length=128)),
                ("task_path", models.CharField(blank=True, max_length=255)),
                ("enqueued", models.PositiveIntegerField(default=0)),
                ("started", models.PositiveIntegerField(default=0)),
                ("succeeded", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("abandoned", models.PositiveIntegerField(default=0)),
                ("runtime_ms_sum", models.PositiveBigIntegerField(default=0)),
                ("runtime_ms_p50", models.PositiveBigIntegerField(default=0)),
                ("runtime_ms_p95", models.PositiveBigIntegerField(default=0)),
                ("runtime_ms_max", models.PositiveBigIntegerField(default=0)),
                ("wait_ms_sum", models.PositiveBigIntegerField(default=0)),
                ("wait_ms_max", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-bucket_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_start", "queue_name", "task_path"),
                        name="overseer_bucket_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=64, unique=True)),
                ("backend", models.CharField(max_length=64)),
                ("attempt", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                            ("ABANDONED", "Abandoned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="READY",
                        max_length=16,
                    ),
                ),
                (
                    "enqueued_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "worker_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("exception_class", models.CharField(blank=True, max_length=255)),
                ("traceback", models.TextField(blank=True)),
                ("return_value", models.JSONField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("wait_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="overseer.job",
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="overseer.run",
                    ),
                ),
            ],
            options={
                "ordering": ["-enqueued_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("task_path", models.CharField(max_length=255)),
                (
                    "cron",
                    models.CharField(
                        blank=True,
                        help_text="Five-field cron expression",
                        max_length=100,
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("queue_name", models.CharField(blank=True, max_length=128)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("backend", models.CharField(blank=True, max_length=64)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("declared_in_code", models.BooleanField(default=False)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("runs_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="overseer.job",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    ("manage_schedules", "Can pause, resume and trigger schedules")
                ],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="overseer.schedule",
            ),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.CharField(max_length=255, unique=True)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("pid", models.PositiveIntegerField(blank=True, null=True)),
                ("backend", models.CharField(blank=True, max_length=64)),
                ("queues", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("tasks_processed", models.PositiveIntegerField(default=0)),
                ("tasks_failed", models.PositiveIntegerField(default=0)),
                (
                    "current_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="overseer.run",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["status", "started_at"], name="overseer_ru_status_ebd003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["job", "attempt"], name="overseer_ru_job_id_85beeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="overseer_jo_status_23f060_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["queue_name", "status"], name="overseer_jo_queue_n_f79d33_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("unique_key", ""), _negated=True),
                    ("status__in", ["PENDING", "RUNNING"]),
                ),
                fields=("unique_key",),
                name="overseer_job_unique_active",
            ),
        ),
    ]
