# Generated by Django 6.1.2 on 2026-10-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overseer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="missing_from_code",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="heartbeat_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
